config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  get "/home/about" => "homes#about"
  get 'users/unsubscribe' => 'users#unsubscribe'
  get '/search', to: 'searches#search'
  resources :users, except: [:new] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorites, only: [:create, :destroy] #いいね機能
      resources :recipe_comments, only: [:create, :destroy] #コメント機能
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attachment :image

  belongs_to :user
  # いいね
  has_many :favorites       , dependent: :destroy
  # いいね順表示
  has_many :favorites_users, through: :favorites, source: :user
  # レシピコメント
  has_many :recipe_comments , dependent: :destroy

  validates :name           , presence: true,    length: { in: 1..40 }
  validates :description    , presence: true,    length: { in: 1..500 }
  validates :procedure      , presence: true,    length: { in: 5..3000 }
  validates :ingredients    , presence: true,    length: { in: 1..1000 }
  validates :calories       , presence: true,    length: { in: 1..30 }
  validates :cost           , presence: true,    length: { in: 1..30 }
  validates :image          , presence: true

  def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Recipe.where(name: content)
    else
      Recipe.where('name LIKE ?', '%'+content+'%')
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :colect_user, only: [:edit, :update]


  def index
      @user = current_user
      @recipecount = Recipe.all
      @recipes = Recipe.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
      @recipe = Recipe.new
  end

  def show
      @recipe = Recipe.find(params[:id])
      @recipes = Recipe.all
      @user = @recipe.user
      @recipe_comment = RecipeComment.new
      @recipe_comments = RecipeComment.where(recipe_id: @recipe.id).order(created_at: :desc).page(params[:page]).per(3)
  end

  def create
      @recipe = Recipe.new(recipe_params)
      @recipe.user_id = current_user.id
      if @recipe.save
        redirect_to recipe_path(@recipe)
      else
        @recipes = Recipe.all
        render 'new'
      end
  end

  def edit
      @recipe = Recipe.find(params[:id])
  end

  def update
      @recipe = Recipe.find(params[:id])
      if @recipe.update(recipe_params)
        redirect_to recipe_path(@recipe)
      else
        render "edit"
      end
  end

  def destroy
      @recipe = Recipe.find(params[:id])
      @recipe.destroy
      redirect_to recipes_path
  end

  private
  def colect_user
    user = Recipe.find(params[:id]).user
    if current_user.id != user.id
      redirect_to recipes_path
    end
  end

  def recipe_params
    params.require(:recipe).permit(:user_id, :name, :description, :procedure, :ingredients, :calories, :cost, :image)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> 件のエラーが発生したため レシピ は保存されませんでした。</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/recipes/_index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <h1>レシピの"<%= @content %>"で検索(全<%= @recipes.count %>件)</h1>
      <h2><%= link_to '＋新規レシピ登録', new_recipe_path, class: "btn btn-sm btn btn-primary" %></h2>
      <table class="table border border-dark">
        <thead>
          <tr>
            <th class="border border-dark">&emsp;&emsp;写真</th>
            <th class="border border-dark">&emsp;レシピ説明</th>
            <th class="border border-dark">&emsp;材料</th>
            <th class="border border-dark">&emsp;詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
            <tr>
              <td class="border border-dark">
                <%= link_to recipe_path(recipe.id) do %>
                  <%= attachment_image_tag recipe, :image, :fill, 250, 150 %>
                <% end %>
                <p class="text-danger"><%= link_to recipe.name, recipe_path(recipe.id), class: "btn btn-sm btn btn-outline-primary" %>
                <!--いいね数表示-->
                  <%= recipe.favorites.count %><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                </p>
              </td>
              <td class="border border-dark" width="20%"><%= recipe.description %></td>
              <td class="border border-dark"><%= recipe.ingredients %></td>
              <td class="border border-dark" width="15%"><%= link_to 'レシピ詳細', recipe_path(recipe), class: "btn btn-sm btn btn-outline-primary recipe_#{recipe.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <!--kaminariで１０件表示 -->
        <%= paginate @recipes %>
      </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<main>
  <div class="container">
    <%= render 'recipes/error', model: @recipe %>
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1><%= @recipe.name %>を編集する</h1>
        <%= form_with model:@recipe, url: recipe_path(@recipe), local:true do |f| %>
          <div class="form-group">
            <label for="recipe_image">レシピ画像</label>
            <%= f.attachment_field:image %>
          </div>

          <div class="form-group">
            <label for="recipe_name">レシピ名</label>
            <%= f.text_field:name, size: "40" %>
          </div>
          <!--text_areaはtext_fieldのサイズ変更-->
          <div class="form-group">
            <label for="recipe_description">レシピ説明</label>
            <%= f.text_area :description, class:"form-control description" %>
          </div>

          <div class="form-group">
            <label for="recipe_procedure">レシピ説明（調理手順）</label>
            <%= f.text_area :procedure, class:"form-control procedure" %>
          </div>

          <div class="form-group">
            <label for="recipe_ingredients">材料</label>
            <%= f.text_area:ingredients, class:"form-control ingredients" %>
          </div>

          <div class="form-group">
            <label for="recipe_calories">カロリー</label>
            &emsp;&emsp;<%= f.text_field:calories %>kcal
          </div>

          <div class="form-group">
            <label for="recipe_cost">材料費</label>
            &emsp;&emsp;&emsp;<%= f.text_field:cost %>円
          </div>

          <div class="form-group">
            <%= f.submit '変更を保存する' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/recipes/index.html.erb
<div class='container'>
  <div class='row'>
    <h1>レシピ一覧(全<%= @recipecount.count %>件)</h1>&emsp;
    <h2><%= link_to '＋新規レシピ登録', new_recipe_path, class: "btn btn-sm btn btn-primary" %></h2>
      <table class="table border border-dark">
        <thead>
          <tr>
            <th class="border border-dark">&emsp;&emsp;写真</th>
            <th class="border border-dark">&emsp;レシピ説明</th>
            <th class="border border-dark">&emsp;材料</th>
            <th class="border border-dark">&emsp;詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
            <tr>
              <td class="border border-dark">
                <%= link_to recipe_path(recipe.id) do %>
                  <%= attachment_image_tag recipe, :image, :fill, 150, 150 %>
                <% end %>
                <p class="text-danger"><%= link_to recipe.name, recipe_path(recipe.id), class: "btn btn-sm btn btn-outline-primary" %>
                <!--いいね数表示-->
                  <%= recipe.favorites.count %><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                </p>
              </td>
              <td class="border border-dark" width="20%"><%= recipe.description %></td>
              <td class="border border-dark"><%= recipe.ingredients %></td>
              <!--tableで幅や高さを変えるには<td width="80" height="100">80×100</td>-->
              <td class="border border-dark" width="15%"><%= link_to 'レシピ詳細', recipe_path(recipe), class: "btn btn-sm btn btn-outline-primary recipe_#{recipe.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <div class="kaminari">
      <!--kaminariで１０件表示 -->
      <%= paginate @recipes %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <%= render 'recipes/error', model: @recipe %>
      <div class="col-md-8 mx-auto">
        <h1>レシピ新規登録</h1>
        <%= form_with model:@recipe, url:recipes_path, local:true do |f| %>
          <div class="form-group">
            <label for="recipe_image">レシピ画像</label>
            <%= f.attachment_field:image %>
          </div>

          <div class="form-group">
            <label for="recipe_name">レシピ名</label>
            <%= f.text_field:name, size: "40x20" %>
          </div>
          <!--text_areaはtext_fieldのサイズ変更-->
          <div class="form-group">
            <label for="recipe_description">レシピ説明</label>
            <%= f.text_area:description, class:"form-control description" %>
          </div>

          <div class="form-group">
            <label for="recipe_procedure">レシピ説明（調理手順）</label>
            <%= f.text_area:procedure, class:"form-control procedure" %>
          </div>

          <div class="form-group">
            <label for="recipe_ingredients">材料</label>
            <%= f.text_area:ingredients, class:"form-control ingredients" %>
          </div>

          <div class="form-group">
            <label for="recipe_procedure">カロリー</label>
            &emsp;&emsp;<%= f.text_field:calories %>kcal
          </div>

          <div class="form-group">
            <label for="recipe_cost">材料費</label>
            &emsp;&emsp;&emsp;<%= f.text_field:cost %>円
          </div>

          <div class="form-group">
            <%= f.submit '新規作成', class:"btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <!--レシピ詳細を表示-->
      <h2><%= @recipe.name %>の詳細</h2>
      <% if user_signed_in? %>
        <% if @recipe.user.id == current_user.id %>
          <%= link_to 'このレシピを編集する', edit_recipe_path(@recipe), class: "btn btn-sm btn-success edit_recipe_#{@recipe.id}" %>
          <%= link_to 'このレシピを削除する',recipe_path(@recipe), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_recipe_#{@recipe.id}"%>
        <% end %>
      <% end %>
        <table class="table border border-dark">
          <thead>
            <th>ニックネーム</th>
            <th>レシピ投稿日時</th>
            <th>カロリー</th>
            <th>材料費</th>
            <th>いいね</th>
          </thead>
          <tbody>
            <tr>
              <td><%= link_to @user.nickname, user_path(@user), class: "btn btn-sm btn btn-outline-primary user_#{@user.id}" %></td>
              <td><%= @recipe.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= @recipe.calories %>kcal</td>
              <td><%= @recipe.cost %>円</td>
                <td>
                  <% if user_signed_in? && current_user != @user %>
                  <!--いいね機能-->
                    <% if @recipe.favorited_by?(current_user) %>
                      <%= link_to recipe_favorites_path(@recipe), class: "btn btn-sm btn btn-outline-danger", method: :delete do %>
                      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= @recipe.favorites.count %>like
                      <% end %>
                    <% else %>
                      <%= link_to recipe_favorites_path(@recipe), class: "btn btn-sm btn btn-outline-danger", method: :post do %>
                      <i class="fa fa-heart-o" aria-hidden="true"></i>
                      <%= @recipe.favorites.count%>like
                      <% end %>
                    <% end %>
                  <% else %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i><%= @recipe.favorites.count %>
                  <% end %>
                </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="container mt-3">
  <div class="row">
    <div class="col-md-4">
      <%= attachment_image_tag @recipe, :image, :fill, 350, 350 %>
    </div>
    <div class="col-md-8 border border-primary">
      <h3><%= @recipe.name %>の説明</h3>
      <!--<%#=safe_join(@text.split("\n"),tag(:br))%>で改行も表示させる-->
      <%=safe_join(@recipe.description.split("\n"),tag(:br))%>
    </div>
  </div>
</div>
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-4 border border-primary">
        <h3><%= @recipe.name %>の材料</h3>
        <%=safe_join(@recipe.ingredients.split("\n"),tag(:br))%>
    </div>
    <div class="col-lg-8 border border-primary">
      <h3><%= @recipe.name %>の調理手順</h3>
      <%=safe_join(@recipe.procedure.split("\n"),tag(:br))%>
    </div>
  </div>
</div>
<div class="container mt-3">
  <div class="row">
    <%= render 'recipe_comments/error', model: @recipe_comment %>
  </div>
</div>
<!--<div class="container">-->
  <div class="row">
    <% if user_signed_in? %>
      <div class="col-md-1 offset-md-1">
        <%= form_with model:[@recipe,@recipe_comment], local: true do |f| %>
          <%= f.text_area :comment, :placeholder => "コメントする", size:"25x5" %><br>
          <%= f.submit '送信'%>
        <% end %>
      </div>
    <% end %>
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover table-inverse">
        <tbody>
          <div class="card-list-container pt-6row">
            <!--コメント-->
          <h3><%= @recipe.name %>のコメント一覧(全<%= @recipe.recipe_comments.count %>件)</h3>
            <% @recipe_comments.each do |recipe_comment| %>
              <% recipe_comment_user = recipe_comment.user %>
                <td>
              		<%= link_to user_path(recipe_comment_user), class: "btn btn-sm btn btn-outline-primary user_#{recipe_comment_user.id}" do %>
                		<%= recipe_comment.user.nickname %>
              		<% end %>
    	            <p><%= recipe_comment.comment %></p>
                  <p><% if current_user == recipe_comment_user %>
                    	 <%= link_to 'Destroy', recipe_recipe_comment_path(recipe_comment.recipe_id, recipe_comment.id), class: 'btn-sm btn-danger', method: :delete %>
                  	 <% end %>
                  </p>
    	          </td>
            <% end %>
          </div>
        </tbody>
      </table>
      <div>
        <!--kaminariで3件表示 -->
        <%= paginate @recipe_comments %>
      </div>
    </div>
  </div>
<!--</div>-->