config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  get "/home/about" => "homes#about"
  get 'users/unsubscribe' => 'users#unsubscribe'
  get '/search', to: 'searches#search'
  resources :users, except: [:new] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorites, only: [:create, :destroy] #いいね機能
      resources :recipe_comments, only: [:create, :destroy] #コメント機能
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :recipes       , dependent: :destroy
          # いいね
          has_many :favorites     , dependent: :destroy
          # いいね順表示
          has_many :favorites_users, through: :favorites, source: :recipe
          # レシピコメント
          has_many :recipe_comments, dependent: :destroy
          # フォローをした、されたの関係
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          # 一覧画面で使う
          has_many :followings    , through: :relationships, source: :followed, dependent: :destroy
          has_many :followers     , through: :reverse_of_relationships, source: :follower, dependent: :destroy

          validates :first_name   , presence: true,    length: { in: 1..20 }
          validates :last_name    , presence: true,    length: { in: 1..20 }
          validates :nickname     , presence: true,    uniqueness: true,        length: { in: 1..30 }

          VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
          validates :email, presence: true,
                    length: { maximum: 255 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }


          # フォローしたときの処理
          def follow(user_id)
            relationships.create(followed_id: user_id)
          end
          # フォローを外すときの処理
          def unfollow(user_id)
            relationships.find_by(followed_id: user_id).destroy
          end
          # フォローしているか判定
          def following?(user)
            followings.include?(user)
          end

          def self.search_for(content, method)
            if method == 'perfect'
              User.where(nickname: content)
            else
              User.where('nickname LIKE ?', '%' + content + '%')
            end
          end

  def full_name
    self.first_name + " " + self.last_name  # 姓と名の間にスペースを追加
  end

  private

  def downcase_email
    self.email = self.email.downcase
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show,]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :set_user, only: [:followings, :followers]

  def index
      @user = current_user
      @usercount = User.all
      @users = User.all.page(params[:page]).per(10)
      @recipe = Recipe.new
      @recipes = Recipe.all
  end

  def show
      @user = User.find(params[:id])
      @recipe = Recipe.new
      @recipes = @user.recipes.page(params[:page]).per(5)
      if user_signed_in?
        favorites = Favorite.where(user_id: current_user.id).pluck(:recipe_id)  # ログイン中のユーザーのお気に入りのrecipe_idカラムを取得
        @favorite_list = Recipe.find(favorites)     # recipesテーブルから、お気に入り登録済みのレコードを取得
      end
  end

  def edit
      @user = User.find(params[:id])
      if @user == current_user
        render "edit"
      else
        redirect_to user_path(current_user)
      end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(current_user)
      else
        render "edit"
      end
  end

  def unsubscribe

  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
       redirect_to :root
  end

  def followings
     user = User.find(params[:user_id])
     @users = user.followegs
  end

  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end

  private
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  def user_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> 件のエラーが発生したため ユーザー は保存されませんでした。</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <!--ユーザー一覧を表示-->
      <h1>ユーザーの"<%= @content %>"さんで検索(全<%= @users.count %>人)</h1>
      <% if user_signed_in? %>
        <% if @user.id == current_user.id %>
          <%= link_to 'マイページを確認する', user_path(@user), class: "btn btn-sm btn-success" %>
        <% end %>
      <% end %>
        <table class="table border border-dark">
          <thead>
            <th>&emsp;ニックネーム</th>
            <th>&emsp;レシピ投稿数</th>
            <th>&emsp;フォロー数</th>
            <th>&emsp;フォロワー数</th>
            <th>&emsp;ユーザー詳細</th>
          </thead>
          <tbody>
          <!--ユーザー情報を表示-->
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.nickname, user_path(user), class: "btn btn-sm btn btn-outline-primary user_#{user.id}" %></td>
              <td>&emsp;&emsp;<%= user.recipes.count %></td>
              <td>&emsp;&emsp;&emsp;<%= user.followings.count %></td>
              <td>&emsp;&emsp;<%= user.followers.count %></td>
              <td><%= link_to 'ユーザー詳細', user_path(user), class: "btn btn-sm btn btn-outline-primary user_#{user.id}" %></td>
            </tr>
          <% end %>
          </tbody>
      </table>
      <div>
        <!--kaminariで１０件表示 -->
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <%= render 'users/error', model: @user %>
    <div class="row">
      <div class="col-md-12 offset-md-3">
        <h1>マイページを編集する</h1>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="user_name">名前</label><br>
            <%= f.label :（姓） %><%= f.text_field :first_name %><%= f.label :（名）%><%= f.text_field :last_name %>
          </div>
          
          <div class="form-group">
            <label for="user_nickname">ニックネーム</label>&emsp;&emsp;&emsp;&emsp;
            <%= f.text_field :nickname %>
          </div>
          
          <div class="form-group">
            <label for="user_email">メールアドレス</label>&emsp;&emsp;&emsp;
            <%= f.email_field :email %>
          </div>
        
          <div class="form-group">
            <%= f.submit '変更を保存' %>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            <%= link_to "退会する", users_unsubscribe_path, class: "btn btn-sm btn btn-outline-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <!--ユーザー一覧を表示-->
      <h2>ユーザー一覧(全<%= @usercount.count %>人)</h2>
      <% if user_signed_in? %>
        <% if @user.id == current_user.id %>
          <%= link_to 'マイページを確認する', user_path(@user), class: "btn btn-sm btn-success" %>
        <% end %>
      <% end %>
      <table class="table border border-dark">
        <thead>
          <th>ニックネーム</th>
          <th>レシピ投稿数</th>
          <th>フォロー数</th>
          <th>フォロワー数</th>
          <th>ユーザー詳細</th>
        </thead>
        <tbody>
          <!--ユーザー情報を表示-->
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.nickname, user_path(user), class: "btn btn-sm btn btn-outline-primary user_#{user.id}" %></td>
              <td>&emsp;&emsp;<%= user.recipes.count %></td>
              <td>&emsp;&emsp;<%= user.followings.count %></td>
              <td>&emsp;&emsp;<%= user.followers.count %></td>
              <td><%= link_to 'ユーザー詳細', user_path(user), class: "btn btn-sm btn btn-outline-primary user_#{user.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <!--kaminariで１０件表示 -->
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <!--ユーザー一覧を表示-->
      <h1><%= @user.nickname %>さんの詳細</h1>
      <% if user_signed_in? %>
        <% if @user.id == current_user.id %>
          <%= link_to 'マイページを編集する', edit_user_path(@user), class: "btn btn-sm btn-success edit_user_#{@user.id}" %>
        <% end %>
      <% end %>
        <table class="table border border-dark">
          <thead>
            <th>ニックネーム</th>
            <th>レシピ投稿数</th>
            <% if user_signed_in? && current_user != @user %>
              <th>&emsp;フォロー</th>
            <% end %>
            <th>フォロー一覧</th>
            <th>フォロワー一覧</th>
          </thead>
          <tbody>
          <!--ユーザー情報を表示-->
            <tr>
              <td><%= @user.nickname %></td>
              <td>&emsp;&emsp;<%= @user.recipes.count %></td>
              <% if user_signed_in? && current_user != @user %>
                <td>
                  <% if current_user.following?(@user) %>
                    <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-sm  btn-outline-success" %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-sm  btn-outline-success" %>
                  <% end %>
                </td>
              <% end %>
              <td>
                <%= link_to user_followings_path(@user), class: "btn btn-sm  btn-outline-info" do %>
                  <%= @user.followings.count %> フォロー
                <% end %>
              </td>
              <td>
                <%= link_to user_followers_path(@user), class: "btn btn-sm  btn-outline-info" do %>
                  <%= @user.followers.count %> フォロワー
                <% end %>
              </td>
            </tr>
          </tbody>
      </table>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class="col-md-12">
    <!--ユーザーレシピ表示-->
      <h4><%= @user.nickname %>さんの投稿レシピ一覧(全<%= @user.recipes.count %>件)</h4>
      <table class="table border border-dark">
        <thead>
          <tr>
            <th class="border border-dark">写真</th>
            <th class="border border-dark">レシピ説明</th>
            <th class="border border-dark">材料</th>
            <th class="border border-dark">詳細リンク</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
            <tr>
              <td class="border border-dark">
                <%= link_to recipe_path(recipe.id) do %>
                  <%= attachment_image_tag recipe, :image, :fill, 150, 150 %>
                <% end %>
                <p class="text-danger"><%= link_to recipe.name, recipe_path(recipe.id), class: "btn btn-sm btn btn-outline-primary" %>
                <!--レシピいいね数表示-->
                  <%= recipe.favorites.count %><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                </p>
              </td>
              <td class="border border-dark" width="20%"><%= recipe.description %></td>
              <td class="border border-dark"><%= recipe.ingredients %></td>
              <!--tableで幅や高さを変えるには<td width="80" height="100">80×100</td>-->
              <td class="border border-dark" width="15%"><%= link_to 'レシピ詳細', recipe_path(recipe), class: "btn btn-sm btn btn-outline-primary recipe_#{recipe.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <!--kaminariで5件表示 -->
        <%= paginate @recipes %>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 offset-md-4">
     <h1 class="font-weight-bold mt-5">本当に退会しますか？</h1>
     <p class="my-5">
     退会すると、会員登録情報が<br>
     全て削除され、投稿したレシピなども削除されます。<br>
     退会する場合は、「退会する」をクリックしてください。
     </p>
     <%= link_to '退会しない', root_path, data: {"turbolinks" => false}, class:"btn btn btn btn-primary mx-3" ,style:"width:150px" %>
     <%= link_to "退会する",user_path(current_user.id), class: "destroy-user", method: :delete, "data-confirm" => "本当に退会しますか？",class:"btn btn-danger mx-3" ,style:"width:150px" %>
    </div>
  </div>
</div>