config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  get "/home/about" => "homes#about"
  get 'users/unsubscribe' => 'users#unsubscribe'
  get '/search', to: 'searches#search'
  resources :users, except: [:new] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorites, only: [:create, :destroy] #いいね機能
      resources :recipe_comments, only: [:create, :destroy] #コメント機能
  end
end

app/views/layouts/_footer.html.erb
<footer >
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>©2021 bookdodolce.net </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    <%= link_to root_path, data: {"turbolinks" => false} do %>
      <%= image_tag 'logo.jpg', class: "image", size: "80x80" %>
    <% end %>
  </a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item active"><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' レシピ一覧',recipes_path,class: 'fas fa-book nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' ユーザー一覧',users_path,class: 'fas fa-users nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' ログアウト', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
      <% else %>
        <li class="nav-item active"><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' レシピ一覧',recipes_path,class: 'fas fa-home nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' ユーザー一覧',users_path,class: 'fas fa-users nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' 新規登録', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
        <li class="nav-item active"><%= link_to ' ログイン', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
      <% end %>
    </ul>
    <%= render 'layouts/seach' %>
  </div>
</nav>

app/views/layouts/_seach.html.erb
<div class="serch_form float-right">
    <%= form_with url: search_path,method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model,options_for_select({"レシピ"=>"recipe","ユーザー"=>"user"})%>
    <%= f.select :method,options_for_select({"部分一致"=>"partial","完全一致"=>"perfect"})%>
    <%= f.submit'検索' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookDoDolce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!--slickの呼び出し-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>


  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>